"""
Comparison Script for AKILES2D Python vs MATLAB Results

This script loads the JSON results generated by the Python examples and the MATLAB port examples
and generates comparison plots for validation and documentation purposes.

Usage:
    uv run docs/scripts/generate_plots.py
    
Expects the following files to exist (after running examples):
    - examples/python/potential_density_results.json
    - examples/python/temperature_heatflux_results.json
    - examples/python/eedf_slices_results.json
    - matlab_port/examples/sims_potential_density/potential_density_results.json
    - matlab_port/examples/sims_temperature_heatflux/temperature_heatflux_results.json
    - matlab_port/examples/sims_eedf_slices/eedf_slices_results.json
    
If MATLAB files are missing, it will generate plots using only Python data (where possible).
"""

import json
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

def load_json(path):
    if not Path(path).exists():
        print(f"Warning: File {path} not found.")
        return None
    with open(path) as f:
        data = json.load(f)
    return {k: np.array(v) for k, v in data.items()}

def clean_h(h):
    # Convert 'inf' to np.inf if present
    h_clean = []
    for val in h:
        if isinstance(val, str) and 'inf' in val.lower():
            h_clean.append(np.inf)
        else:
            h_clean.append(float(val))
    return np.array(h_clean)

def plot_potential_density():
    print("Generating Potential/Density comparison plot...")
    py_path = "examples/python/potential_density_results.json"
    ml_path = "matlab_port/examples/sims_potential_density/potential_density_results.json"
    
    py_data = load_json(py_path)
    ml_data = load_json(ml_path)
    
    if py_data is None: return

    fig, ax1 = plt.subplots(figsize=(8, 5))
    
    h_py = clean_h(py_data["h"])
    mask_py = np.isfinite(h_py)
    
    # Plot Python
    l1, = ax1.plot(h_py[mask_py], py_data["phi"][mask_py], 'b-', label=r"$\phi$ (Python)")
    ax1.set_xlabel("Normalized position h")
    ax1.set_ylabel("Potential (V)", color='b')
    ax1.tick_params(axis='y', labelcolor='b')
    
    ax2 = ax1.twinx()
    l2, = ax2.plot(h_py[mask_py], py_data["ne"][mask_py], 'r-', label=r"$n_e$ (Python)")
    l3, = ax2.plot(h_py[mask_py], py_data["ni"][mask_py], 'g-', label=r"$n_i$ (Python)")
    ax2.set_ylabel("Density (normalized)")

    lines = [l1, l2, l3]

    if ml_data:
        h_ml = clean_h(ml_data["h"])
        mask_ml = np.isfinite(h_ml)
        
        # Plot MATLAB (dashed)
        l4, = ax1.plot(h_ml[mask_ml], ml_data["phi"][mask_ml], 'b--', alpha=0.7, label=r"$\phi$ (MATLAB)")
        l5, = ax2.plot(h_ml[mask_ml], ml_data["ne"][mask_ml], 'r--', alpha=0.7, label=r"$n_e$ (MATLAB)")
        l6, = ax2.plot(h_ml[mask_ml], ml_data["ni"][mask_ml], 'g--', alpha=0.7, label=r"$n_i$ (MATLAB)")
        lines.extend([l4, l5, l6])

    ax1.set_title("Comparison: Potential and Density")
    ax1.legend(lines, [l.get_label() for l in lines], loc='center right')
    ax1.grid(True, alpha=0.3)
    
    fig.tight_layout()
    fig.savefig("docs/potential_density_comparison.png", dpi=150)
    plt.close(fig)

def plot_thermodynamics():
    print("Generating Thermodynamics comparison plot...")
    py_path = "examples/python/temperature_heatflux_results.json"
    ml_path = "matlab_port/examples/sims_temperature_heatflux/temperature_heatflux_results.json"
    
    py_data = load_json(py_path)
    ml_data = load_json(ml_path)
    
    if py_data is None: return

    # Fig 02 usually doesn't save 'h', it saves 'r'. But let's assume 'r' maps to position if 'h' is missing
    # Actually wait, the example script saves 'r', 'Tz_e', etc.
    # We need an x-axis. Using generic index or 'r' if it corresponds to position.
    # In AKILES2D, h is the grid. The example should have saved h.
    # Let's check keys. If h is missing, we use index.
    
    # Update: Looking at previous context, fig02 saved 'r', 'Tz_e', etc. but NOT 'h'. 
    # 'r' is the radius of the flux tube but mapped to 'h'.
    # We will assume a simple linspace or use 'r' if it's monotonic.
    # For meaningful comparison, plotting against index is safer if grids match.
    
    n_pts = len(py_data["Tz_e"])
    x = np.arange(n_pts)
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    # Temperatures
    ax1.plot(x, py_data["Tz_e"], 'b-', label=r"$T_{\parallel e}$ (Py)")
    ax1.plot(x, py_data["Tr_e"], 'r-', label=r"$T_{\perp e}$ (Py)")
    
    if ml_data:
        ax1.plot(x, ml_data["Tz_e"], 'b--', alpha=0.7, label=r"$T_{\parallel e}$ (ML)")
        ax1.plot(x, ml_data["Tr_e"], 'r--', alpha=0.7, label=r"$T_{\perp e}$ (ML)")
        
    ax1.set_title("Temperatures")
    ax1.set_ylabel("Temperature (normalized)")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Heat Flux
    ax2.plot(x, py_data["qzz_e"], 'b-', label=r"$q_{z}$ (Py)")
    if ml_data:
         ax2.plot(x, ml_data["qzz_e"], 'b--', alpha=0.7, label=r"$q_{z}$ (ML)")
         
    ax2.set_title("Heat Flux")
    ax2.set_ylabel("Heat Flux (normalized)")
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    fig.tight_layout()
    fig.savefig("docs/thermodynamics_comparison.png", dpi=150)
    plt.close(fig)

def plot_eedf():
    print("Generating EEDF comparison plot...")
    py_path = "examples/python/eedf_slices_results.json"
    ml_path = "matlab_port/examples/sims_eedf_slices/eedf_slices_results.json"
    
    py_data = load_json(py_path)
    ml_data = load_json(ml_path)
    
    if py_data is None: return
    
    # py_data['Ek'] is list of lists
    # py_data['EEDF'] is list of lists
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    colors = ['b', 'g', 'r']
    labels = ["Injection", "Mid plume", "Far plume"]
    
    Ek_py = np.array(py_data["Ek"])
    EEDF_py = np.array(py_data["EEDF"])
    
    for i in range(len(colors)):
        if i >= len(Ek_py): break
        ax.plot(Ek_py[i], EEDF_py[i], color=colors[i], linestyle='-', label=f"{labels[i]} (Py)")
        
        if ml_data:
             Ek_ml = np.array(ml_data["Ek"])
             EEDF_ml = np.array(ml_data["EEDF"])
             if i < len(Ek_ml):
                 ax.plot(Ek_ml[i], EEDF_ml[i], color=colors[i], linestyle='--', alpha=0.7, label=f"{labels[i]} (ML)")
    
    ax.set_yscale("log")
    ax.set_xlabel("Energy (normalized)")
    ax.set_ylabel("EEDF (a.u.)")
    ax.set_title("EEDF Comparison")
    ax.set_ylim(1e-13, 1e2)
    ax.set_xlim(0, 20)
    ax.legend(loc='lower left')
    ax.grid(True, alpha=0.3)
    
    fig.tight_layout()
    fig.savefig("docs/eedf_comparison.png", dpi=150)
    plt.close(fig)

if __name__ == "__main__":
    plot_potential_density()
    plot_thermodynamics()
    plot_eedf()
    print("All comparison plots generated in docs/")
